In [33]:
import numpy as np

In [34]:
array_2D = np.array([[0. , 0.5, 1. , 1.5, 2. ],
                     [2.5, 3. , 3.5, 4. , 4.5],
                     [5. , 5.5, 6. , 6.5, 7. ],
                     [7.5, 8. , 8.5, 9. , 9.5]])

(4.3.3)=
## 4.3.3 Advanced Indexing

```{index} fancy indexing
```

In the event you have a multidimensional array, you can access elements in the array using multiple collections of values (i.e., ndarrays, lists, or tuples) where each collection indicates the location along a different dimension. This is an instance of *fancy indexing*. For example, if we want to select the following bolded, orange elements from `array_2D`, we can create two lists - the first list contains the row indicies for each element and the second list likewise contains the column indicies.

$$ \left[ \begin{array}{cCc} 0. & 0.5 & 1. & \color{BurntOrange}\textbf{1.5} & 2. \\ 
                             2.5 & 3. & 3.5 & 4. & 4.5 \\ 
                             \color{BurntOrange}\textbf{5.} & \color{BurntOrange}\textbf{5.5} & 6. & 6.5 & 7. \\
                             7.5 & 8. & 8.5 & 9. & 9.5 \end{array} \right] $$

In [35]:
row = [2,2,0]
col = [0,1,3]

In [36]:
array_2D[row, col]

array([5. , 5.5, 1.5])

Another feature of indexing ndarrays is that the returned array will have the same dimensions as the array containing the indicies. In the following example, we have two index arrays where `i_flat` is a 1 $\times$ 4 array while `i_square` is a 2 $\times$ 2 array resulting in 1 $\times$ 4 and 2 $\times$ 2 arrays, respectively

In [49]:
threes = np.arange(3, 30, 3)

i_flat = np.array([0, 3,1, 5])
i_square = np.array([[0, 3],
                     [1, 5]])

In [51]:
threes[i_flat]

array([ 3, 12,  6, 18])

In [52]:
threes[i_square]

array([[ 3, 12],
       [ 6, 18]])

The latter result can also be accomplished by indexing using a flat (i.e., one-dimensional) array following by reshaping it to the desired dimensions as demonstred below.

In [38]:
i = np.array([0, 3,1, 5])

threes[i].reshape((2,2))

array([[ 3, 12],
       [ 6, 18]])

(4.3.4)=
## 4.3.4 Masking

```{index} masking
```

Elements in a NumPy array can also be selected using a boolean array through a process known as *masking*. The masking array is a boolean array filled with either `1` and `0` or `True` and `False` and has the same dimensions as the origional array. Any element in the origional array that has a `1` or `True`  in the corresponding masking array is returned. 

For example,

In [39]:
orig_array = np.array([[5, 7, 1],
                       [3, 4, 2],
                       [0, 9, 8]])

mask = np.array([[0, 1, 0],
                 [1, 1, 1],
                 [1, 0, 1]], dtype=bool)

In [40]:
orig_array[mask]

array([7, 3, 4, 2, 0, 8])

It's important to note that if you use `1` and `0` in the masking array, it is critical that you include `dtype=bool` or else NumPy will treat the `1` and `0` as indicies instead of booleans and attempt indexing.

In [41]:
mask = np.array([[0, 1, 0],
                 [1, 1, 1],
                 [1, 0, 1]])

orig_array[mask]

array([[[5, 7, 1],
        [3, 4, 2],
        [5, 7, 1]],

       [[3, 4, 2],
        [3, 4, 2],
        [3, 4, 2]],

       [[3, 4, 2],
        [5, 7, 1],
        [3, 4, 2]]])

The true power of masking is when the masking array is generated through boolean logic. This enables the user to select elements of an array through conditions as demonstrated below where we select all elements of the `org_array` that are greater than 5.

In [42]:
cond = orig_array > 5
cond

array([[False,  True, False],
       [False, False, False],
       [False,  True,  True]])

In [43]:
orig_array[cond]

array([7, 9, 8])

We can also include the condition directly in the square brackets to save a step as shown below.

In [44]:
orig_array[orig_array > 5]

array([7, 9, 8])